### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by fjoshuajr** [reactjs/pt-PT.reactjs.org#10]
I think we should clean up merged branches to keep the repository easy to browse.

Thoughts?

**Comment by telmogoncalves** [comment]
That's fine with me./

**Comment by jbarradas** [comment]
Fine with me too.

**Comment by fjoshuajr** [comment]
👌

**Comment by fjoshuajr** [comment]
From now, after a merge the author shall delete his PR branch.
