### ISSUE TITLE
Glossary and Style Guide

### ISSUE THREAD

**Issue by fjoshuajr** [reactjs/pt-PT.reactjs.org#2]
In addition to a translated [Universal Style Guide](https://github.com/reactjs/reactjs.org-translation/blob/master/style-guide.md).

We need a proper glossary of terms (translatable and non-translatable)

Thoughts?

**Comment by telmogoncalves** [comment]
[Universal Style Guide](https://github.com/reactjs/reactjs.org-translation/blob/master/style-guide.md) would be a good first page to translate since it's the foundation of it.

We can create an issue with all of the **translatable** and **non-translatable** words. Guess that would be the way to go.

**Comment by fjoshuajr** [comment]
Closing in favor of #9
