### ISSUE TITLE
Translated external links

### ISSUE THREAD

**Issue by jbarradas** [reactjs/pt-PT.reactjs.org#4]
@tesseralis @telmogoncalves @fjoshuajr 
Regarding external links, when no pt-PT is available, but pt-BR is available with a decent translation. Which one do you prefer to link? pt-BR or EN?

In my opinion, if someone is reading the portuguese version of the documents, will prefer reading external links in portuguese (brazil) rather than english.

Example:
en-US: https://developer.mozilla.org/en-US/docs/Web/JavaScript/A_re-introduction_to_JavaScript
or
pt-BR: https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/A_re-introduction_to_JavaScript

**Comment by telmogoncalves** [comment]
Yeah, I guess `pt-BR` would be better as long as the translation is already available.

**Comment by fjoshuajr** [comment]
> Yeah, I guess `pt-BR` would be better as long as the translation is already available.

Me too.

**Comment by jbarradas** [comment]
Thanks for the prompt responses!
